services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      AUTH_GUARD: api

      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite

      JWT_TTL: 60
      JWT_ALGO: HS256
      PORT: 8000
    volumes:
      - auth_sqlite:/var/www/html/database
      - auth_storage:/var/www/html/storage

volumes:
  auth_sqlite:
  auth_storage:
